BOOK_002-Genesis := Genesis build/json/WEB/02-GENeng-web.json build/json/WEBBE/02-GENeng-webbe.json build/json/Brenton/02-GENeng-Brenton.json 
BOOK_003-Exodus := Exodus build/json/WEB/03-EXOeng-web.json build/json/WEBBE/03-EXOeng-webbe.json build/json/Brenton/03-EXOeng-Brenton.json 
BOOK_004-Leviticus := Leviticus build/json/WEB/04-LEVeng-web.json build/json/WEBBE/04-LEVeng-webbe.json build/json/Brenton/04-LEVeng-Brenton.json 
BOOK_005-Numbers := Numbers build/json/WEB/05-NUMeng-web.json build/json/WEBBE/05-NUMeng-webbe.json build/json/Brenton/05-NUMeng-Brenton.json 
BOOK_006-Deuteronomy := Deuteronomy build/json/WEB/06-DEUeng-web.json build/json/WEBBE/06-DEUeng-webbe.json build/json/Brenton/06-DEUeng-Brenton.json 
BOOK_007-Joshua := Joshua build/json/WEB/07-JOSeng-web.json build/json/WEBBE/07-JOSeng-webbe.json build/json/Brenton/07-JOSeng-Brenton.json 
BOOK_008-Judges := Judges build/json/WEB/08-JDGeng-web.json build/json/WEBBE/08-JDGeng-webbe.json build/json/Brenton/08-JDGeng-Brenton.json 
BOOK_009-Ruth := Ruth build/json/WEB/09-RUTeng-web.json build/json/WEBBE/09-RUTeng-webbe.json build/json/Brenton/09-RUTeng-Brenton.json 
BOOK_010-1_Samuel := 1_Samuel build/json/WEB/10-1SAeng-web.json build/json/WEBBE/10-1SAeng-webbe.json build/json/Brenton/10-1SAeng-Brenton.json build/json/Prideaux/10-Prideaux-1SA.json
BOOK_011-2_Samuel := 2_Samuel build/json/WEB/11-2SAeng-web.json build/json/WEBBE/11-2SAeng-webbe.json build/json/Brenton/11-2SAeng-Brenton.json build/json/Prideaux/11-Prideaux-2SA.json
BOOK_012-1_Kings := 1_Kings build/json/WEB/12-1KIeng-web.json build/json/WEBBE/12-1KIeng-webbe.json build/json/Brenton/12-1KIeng-Brenton.json build/json/Prideaux/12-Prideaux-1KI.json
BOOK_013-2_Kings := 2_Kings build/json/WEB/13-2KIeng-web.json build/json/WEBBE/13-2KIeng-webbe.json build/json/Brenton/13-2KIeng-Brenton.json 
BOOK_014-1_Chronicles := 1_Chronicles build/json/WEB/14-1CHeng-web.json build/json/WEBBE/14-1CHeng-webbe.json build/json/Brenton/14-1CHeng-Brenton.json 
BOOK_015-2_Chronicles := 2_Chronicles build/json/WEB/15-2CHeng-web.json build/json/WEBBE/15-2CHeng-webbe.json build/json/Brenton/15-2CHeng-Brenton.json 
BOOK_016-Ezra := Ezra build/json/WEB/16-EZReng-web.json build/json/WEBBE/16-EZReng-webbe.json build/json/Brenton/16-EZReng-Brenton.json 
BOOK_017-Nehemiah := Nehemiah build/json/WEB/17-NEHeng-web.json build/json/WEBBE/17-NEHeng-webbe.json build/json/Brenton/17-NEHeng-Brenton.json 
BOOK_018-Esther := Esther build/json/WEB/18-ESTeng-web.json build/json/WEBBE/18-ESTeng-webbe.json build/json/Brenton/43-ESGeng-Brenton.json build/json/Prideaux/43-ESGAeng-Prideaux.json
BOOK_019-Job := Job build/json/WEB/19-JOBeng-web.json build/json/WEBBE/19-JOBeng-webbe.json build/json/Brenton/19-JOBeng-Brenton.json 
BOOK_020-Psalms := Psalms build/json/WEB/20-PSAeng-web.json build/json/WEBBE/20-PSAeng-webbe.json build/json/Brenton/20-PSAeng-Brenton.json 
BOOK_021-Proverbs := Proverbs build/json/WEB/21-PROeng-web.json build/json/WEBBE/21-PROeng-webbe.json build/json/Brenton/21-PROeng-Brenton.json 
BOOK_022-Ecclesiastes := Ecclesiastes build/json/WEB/22-ECCeng-web.json build/json/WEBBE/22-ECCeng-webbe.json build/json/Brenton/22-ECCeng-Brenton.json 
BOOK_023-Song_of_Solomon := Song_of_Solomon build/json/WEB/23-SNGeng-web.json build/json/WEBBE/23-SNGeng-webbe.json build/json/Brenton/23-SNGeng-Brenton.json 
BOOK_024-Isaiah := Isaiah build/json/WEB/24-ISAeng-web.json build/json/WEBBE/24-ISAeng-webbe.json build/json/Brenton/24-ISAeng-Brenton.json 
BOOK_025-Jeremiah := Jeremiah build/json/WEB/25-JEReng-web.json build/json/WEBBE/25-JEReng-webbe.json build/json/Brenton/25-JEReng-Brenton.json 
BOOK_026-Lamentations := Lamentations build/json/WEB/26-LAMeng-web.json build/json/WEBBE/26-LAMeng-webbe.json build/json/Brenton/26-LAMeng-Brenton.json 
BOOK_027-Ezekiel := Ezekiel build/json/WEB/27-EZKeng-web.json build/json/WEBBE/27-EZKeng-webbe.json build/json/Brenton/27-EZKeng-Brenton.json 
BOOK_028-Daniel := Daniel build/json/WEB/28-DANeng-web.json build/json/WEBBE/28-DANeng-webbe.json build/json/Brenton/66-DAGeng-Brenton.json build/json/Prideaux/61-Prideaux-Dan.json
BOOK_029-Hosea := Hosea build/json/WEB/29-HOSeng-web.json build/json/WEBBE/29-HOSeng-webbe.json build/json/Brenton/29-HOSeng-Brenton.json 
BOOK_030-Joel := Joel build/json/WEB/30-JOLeng-web.json build/json/WEBBE/30-JOLeng-webbe.json build/json/Brenton/30-JOLeng-Brenton.json 
BOOK_031-Amos := Amos build/json/WEB/31-AMOeng-web.json build/json/WEBBE/31-AMOeng-webbe.json build/json/Brenton/31-AMOeng-Brenton.json 
BOOK_032-Obadiah := Obadiah build/json/WEB/32-OBAeng-web.json build/json/WEBBE/32-OBAeng-webbe.json build/json/Brenton/32-OBAeng-Brenton.json 
BOOK_033-Jonah := Jonah build/json/WEB/33-JONeng-web.json build/json/WEBBE/33-JONeng-webbe.json build/json/Brenton/33-JONeng-Brenton.json 
BOOK_034-Micah := Micah build/json/WEB/34-MICeng-web.json build/json/WEBBE/34-MICeng-webbe.json build/json/Brenton/34-MICeng-Brenton.json 
BOOK_035-Nahum := Nahum build/json/WEB/35-NAMeng-web.json build/json/WEBBE/35-NAMeng-webbe.json build/json/Brenton/35-NAMeng-Brenton.json 
BOOK_036-Habakkuk := Habakkuk build/json/WEB/36-HABeng-web.json build/json/WEBBE/36-HABeng-webbe.json build/json/Brenton/36-HABeng-Brenton.json 
BOOK_037-Zephaniah := Zephaniah build/json/WEB/37-ZEPeng-web.json build/json/WEBBE/37-ZEPeng-webbe.json build/json/Brenton/37-ZEPeng-Brenton.json 
BOOK_038-Haggai := Haggai build/json/WEB/38-HAGeng-web.json build/json/WEBBE/38-HAGeng-webbe.json build/json/Brenton/38-HAGeng-Brenton.json 
BOOK_039-Zechariah := Zechariah build/json/WEB/39-ZECeng-web.json build/json/WEBBE/39-ZECeng-webbe.json build/json/Brenton/39-ZECeng-Brenton.json 
BOOK_040-Malachi := Malachi build/json/WEB/40-MALeng-web.json build/json/WEBBE/40-MALeng-webbe.json build/json/Brenton/40-MALeng-Brenton.json 
OT := 002-Genesis 003-Exodus 004-Leviticus 005-Numbers 006-Deuteronomy 007-Joshua 008-Judges 009-Ruth 010-1_Samuel 011-2_Samuel 012-1_Kings 013-2_Kings 014-1_Chronicles 015-2_Chronicles 016-Ezra 017-Nehemiah 018-Esther 019-Job 020-Psalms 021-Proverbs 022-Ecclesiastes 023-Song_of_Solomon 024-Isaiah 025-Jeremiah 026-Lamentations 027-Ezekiel 028-Daniel 029-Hosea 030-Joel 031-Amos 032-Obadiah 033-Jonah 034-Micah 035-Nahum 036-Habakkuk 037-Zephaniah 038-Haggai 039-Zechariah 040-Malachi
